name: Auto Process Zip Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  process-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: cluntop/cluntop.github.io
        token: ${{ secrets.GIT_TOKEN }}
        path: target-repo

    - name: Clone source repo
      env:
        GITHUB: ${{ secrets.GITHUB }}
      run: |
        git clone https://github.com/fish2018/PG.git source-repo

    - name: Find and process zip files
      run: |
        cd source-repo
        ZIP_FILE=$(find . -type f -regex ".*/pg\.[0-9]\{8\}-[0-9]\{4\}\.zip" | head -n 1)

        if [ -z "$ZIP_FILE" ]; then
          echo "No zip file found"
          exit 0
        fi

        unzip -o "$ZIP_FILE" -x "README.txt" -d ../target-repo/

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add .
        git commit -m "Update pg" || echo "No changes to commit"
        git push origin HEAD:main